// trending movies and tv shows
export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";
export const GET_TRENDING_MOVIES_LOADING = "GET_TRENDING_MOVIES_LOADING";
export const GET_TRENDING_MOVIES_ERROR = "GET_TRENDING_MOVIES_ERROR";

export const GET_TRENDING_SHOWS = "GET_TRENDING_SHOWS";
export const GET_TRENDING_SHOWS_LOADING = "GET_TRENDING_SHOWS_LOADING";
export const GET_TRENDING_SHOWS_ERROR = "GET_TRENDING_SHOWS_ERROR";

// movies
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_POPULAR_MOVIES_LOADING = "GET_POPULAR_MOVIES_LOADING";
export const GET_POPULAR_MOVIES_ERROR = "GET_POPULAR_MOVIES_ERROR";

export const GET_NOW_PLAYING_MOVIES = "GET_NOW_PLAYING_MOVIES";
export const GET_NOW_PLAYING_MOVIES_LOADING = "GET_NOW_PLAYING_MOVIES_LOADING";
export const GET_NOW_PLAYING_MOVIES_ERROR = "GET_NOW_PLAYING_MOVIES_ERROR";

export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_TOP_RATED_MOVIES_LOADING = "GET_TOP_RATED_MOVIES_LOADING";
export const GET_TOP_RATED_MOVIES_ERROR = "GET_TOP_RATED_MOVIES_ERROR";

export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_UPCOMING_MOVIES_LOADING = "GET_UPCOMING_MOVIES_LOADING";
export const GET_UPCOMING_MOVIES_ERROR = "GET_UPCOMING_MOVIES_ERROR";

// tv shows
export const GET_POPULAR_SHOWS = "GET_POPULAR_SHOWS";
export const GET_POPULAR_SHOWS_LOADING = "GET_POPULAR_SHOWS_LOADING";
export const GET_POPULAR_SHOWS_ERROR = "GET_POPULAR_SHOWS_ERROR";

export const GET_TOP_RATED_SHOWS = "GET_TOP_RATED_SHOWS";
export const GET_TOP_RATED_SHOWS_LOADING = "GET_TOP_RATED_SHOWS_LOADING";
export const GET_TOP_RATED_SHOWS_ERROR = "GET_TOP_RATED_SHOWS_ERROR";

// reset reducers
export const RESET_HOME_REDUCER = "RESET_HOME_REDUCER";
export const RESET_MOVIES_REDUCER = "RESET_MOVIES_REDUCER";
export const RESET_SHOWS_REDUCER = "RESET_SHOWS_REDUCER";
