// trending movies
export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";
export const GET_TRENDING_MOVIES_LOADING = "GET_TRENDING_MOVIES_LOADING";
export const GET_TRENDING_MOVIES_ERROR = "GET_TRENDING_MOVIES_ERROR";

// trending tv shows
export const GET_TRENDING_SHOWS = "GET_TRENDING_SHOWS";
export const GET_TRENDING_SHOWS_LOADING = "GET_TRENDING_SHOWS_LOADING";
export const GET_TRENDING_SHOWS_ERROR = "GET_TRENDING_SHOWS_ERROR";

export const RESET_HOME_STATE = "RESET_HOME_STATE";
