// trending movies and tv shows
export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";
export const GET_TRENDING_MOVIES_LOADING = "GET_TRENDING_MOVIES_LOADING";
export const GET_TRENDING_MOVIES_ERROR = "GET_TRENDING_MOVIES_ERROR";

export const GET_TRENDING_SHOWS = "GET_TRENDING_SHOWS";
export const GET_TRENDING_SHOWS_LOADING = "GET_TRENDING_SHOWS_LOADING";
export const GET_TRENDING_SHOWS_ERROR = "GET_TRENDING_SHOWS_ERROR";

// movies
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_POPULAR_MOVIES_LOADING = "GET_POPULAR_MOVIES_LOADING";
export const GET_POPULAR_MOVIES_ERROR = "GET_POPULAR_MOVIES_ERROR";

export const GET_NOW_PLAYING_MOVIES = "GET_NOW_PLAYING_MOVIES";
export const GET_NOW_PLAYING_MOVIES_LOADING = "GET_NOW_PLAYING_MOVIES_LOADING";
export const GET_NOW_PLAYING_MOVIES_ERROR = "GET_NOW_PLAYING_MOVIES_ERROR";

export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_TOP_RATED_MOVIES_LOADING = "GET_TOP_RATED_MOVIES_LOADING";
export const GET_TOP_RATED_MOVIES_ERROR = "GET_TOP_RATED_MOVIES_ERROR";

export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_UPCOMING_MOVIES_LOADING = "GET_UPCOMING_MOVIES_LOADING";
export const GET_UPCOMING_MOVIES_ERROR = "GET_UPCOMING_MOVIES_ERROR";

// tv shows
export const GET_POPULAR_SHOWS = "GET_POPULAR_SHOWS";
export const GET_POPULAR_SHOWS_LOADING = "GET_POPULAR_SHOWS_LOADING";
export const GET_POPULAR_SHOWS_ERROR = "GET_POPULAR_SHOWS_ERROR";

export const GET_TOP_RATED_SHOWS = "GET_TOP_RATED_SHOWS";
export const GET_TOP_RATED_SHOWS_LOADING = "GET_TOP_RATED_SHOWS_LOADING";
export const GET_TOP_RATED_SHOWS_ERROR = "GET_TOP_RATED_SHOWS_ERROR";

export const GET_AIRING_TODAY_SHOWS = "GET_AIRING_TODAY_SHOWS";
export const GET_AIRING_TODAY_SHOWS_LOADING = "GET_AIRING_TODAY_SHOWS_LOADING";
export const GET_AIRING_TODAY_SHOWS_ERROR = "GET_AIRING_TODAY_SHOWS_ERROR";

export const GET_ON_THE_AIR_SHOWS = "GET_ON_THE_AIR_SHOWS";
export const GET_ON_THE_AIR_SHOWS_LOADING = "GET_ON_THE_AIR_SHOWS_LOADING";
export const GET_ON_THE_AIR_SHOWS_ERROR = "GET_ON_THE_AIR_SHOWS_ERROR";

// details
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const GET_MOVIE_DETAILS_LOADING = "GET_MOVIE_DETAILS_LOADING";
export const GET_MOVIE_DETAILS_ERROR = "GET_MOVIE_DETAILS_ERROR";

export const GET_SHOW_DETAILS = "GET_SHOW_DETAILS";
export const GET_SHOW_DETAILS_LOADING = "GET_SHOW_DETAILS_LOADING";
export const GET_SHOW_DETAILS_ERROR = "GET_SHOW_DETAILS_ERROR";

export const GET_PERSON_DETAILS = "GET_PERSON_DETAILS";
export const GET_PERSON_DETAILS_LOADING = "GET_PERSON_DETAILS_LOADING";
export const GET_PERSON_DETAILS_ERROR = "GET_PERSON_DETAILS_ERROR";

// search results
export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";
export const GET_SEARCH_RESULTS_LOADING = "GET_SEARCH_RESULTS_LOADING";
export const GET_SEARCH_RESULTS_ERROR = "GET_SEARCH_RESULTS_ERROR";
export const ADD_TO_SEARCH_RESULTS = "ADD_TO_SEARCH_RESULTS";

// reset reducers
export const RESET_HOME_REDUCER = "RESET_HOME_REDUCER";
export const RESET_MOVIES_REDUCER = "RESET_MOVIES_REDUCER";
export const RESET_SHOWS_REDUCER = "RESET_SHOWS_REDUCER";
export const RESET_DETAILS_REDUCER = "RESET_DETAILS_REDUCER";
export const RESET_SEARCH_REDUCER = "RESET_SEARCH_REDUCER";

// export const HOME_LOADING = "HOME_LOADING";
// export const HOME_ERROR = "HOME_ERROR";
